services:
  # Service Redis (utilisé ici pour le rate limiting)
  redis:
    image: redis:7-alpine
    container_name: redis_dev
    restart: always #si le conteneur plante, docker relance automatiquement
    volumes:
      - redis_dev_data:/data #redis stocke ses données dans /data dans le conteneur
    networks:
      - reunionwiki_dev_net

  # Application Flask
  web:
    build: . # Construit l'image depuis le Dockerfile
    container_name: web_dev
    user: "0:0" # Permet d'écrire dans le bind mount /data créé par Docker sur un clone propre
    volumes:
      - ./data_dev:/data # Monte le dossier data pour la persistance des données
      - ./uploads_dev:/app/static/uploads # Uploads persistés hors du conteneur
    restart: always
    environment:
      - FLASK_ENV=production #désactive débug
      - DATABASE_PATH=/data/base.db # Utilise le volume monté pour persister SQLite
      - RATELIMIT_STORAGE_URL=redis://redis_dev:6379/0 # parle au service redis pour le nom interne
    depends_on:
      - redis # Assure que Redis démarre avant l’application Flask
    ports:
      - "8086:8000" # Expose Flask en local sans conflit avec les autres projets
    networks:
      - reunionwiki_dev_net

volumes:
  redis_dev_data: {}

networks:
  reunionwiki_dev_net:
    driver: bridge
